/***************************************************************************************************
Class Name: Enterprise_ServiceLayer_CaseHandling
Class Type: Enterprise Model Service Layer Class
Version     : 1.0
Created Date: 29 March 2017
Function    : Serves as a gateway for common functionality shared across clients like VF Controller, APEX Rest, EmailHandler,
							JS Remoting, Web Services, Batch and Scheduler Apex
Input Parameters: TBD
Output Parameters: TBD
Description:   This class is handles all functionality associated with Case object.
Modification Log :
* Developer                   Date                   Description
* ----------------------------------------------------------------------------
* JRK                        03/29/2016              Created
****************************************************************************************************/
global class Enterprise_ServiceLayer_CaseHandling{

		global static void checkandupdateContact(){

		}

		//global static void 
}